# Generated by Django 4.0.5 on 2022-06-26 18:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_product_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('price', models.IntegerField(blank=True, default=0)),
                ('type', models.CharField(choices=[('OFFER', 'OFFER'), ('CATEGORY', 'CATEGORY')], max_length=100)),
                ('parentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yandex_product_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('oldId', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('price', models.IntegerField(blank=True, default=0)),
                ('type', models.CharField(choices=[('OFFER', 'OFFER'), ('CATEGORY', 'CATEGORY')], max_length=100)),
                ('parentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yandex_product_app.producthistory')),
            ],
        ),
        migrations.RemoveField(
            model_name='shopunithistory',
            name='parentId',
        ),
        migrations.DeleteModel(
            name='ShopUnit',
        ),
        migrations.DeleteModel(
            name='ShopUnitHistory',
        ),
    ]
