# Generated by Django 4.0.5 on 2022-06-26 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_product_app', '0002_product_producthistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='parentId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='yandex_product_app.product'),
        ),
    ]
