# Generated by Django 4.0.4 on 2022-06-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_product_app', '0003_alter_product_parentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
