# Generated by Django 4.0.5 on 2022-06-28 19:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_product_app', '0004_alter_product_date_alter_producthistory_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthistory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
